# config/doctrine.yaml
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%env(DB_HOST)%'
        dbname: '%env(DB_NAME)%'
        user: '%env(DB_USER)%'
        password: '%env(DB_PASSWORD)%'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            App:
                type: annotation
                dir: '%kernel.project_dir%/src/Domain'
                prefix: 'App\Domain'
                is_bundle: false
